# Generated by Django 4.1.3 on 2023-08-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NeighborhoodOrProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="property",
            name="Purpose",
            field=models.CharField(
                choices=[("sale", "sale"), ("rent", "rent")],
                default="sale",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="price",
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="neighborhood_or_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="haji_salam.neighborhoodorproject",
            ),
        ),
    ]
