# Generated by Django 4.1.3 on 2023-08-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0002_neighborhoodorproject_property_purpose_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
