# Generated by Django 4.1.3 on 2023-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0003_alter_property_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="type",
            field=models.CharField(
                choices=[
                    ("House", "House"),
                    ("Villa", "Villa"),
                    ("Apartment", "Apartment"),
                    ("Office", "Office"),
                    ("Land", "Land"),
                    ("Shop", "Shop"),
                    ("Market", "Market"),
                    ("Building", "Building"),
                    ("Farm", "Farm"),
                ],
                default="House",
                max_length=35,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="Purpose",
            field=models.CharField(
                choices=[("Sale", "Sale"), ("Rent", "Rent")],
                default="Sale",
                max_length=10,
            ),
        ),
    ]
