# Generated by Django 4.1.3 on 2023-08-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0004_property_type_alter_property_purpose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="neighborhood_or_project",
        ),
        migrations.AddField(
            model_name="property",
            name="area",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="furnishing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="garden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="reception_rooms",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="NeighborhoodOrProject",
        ),
    ]
