# Generated by Django 4.1.3 on 2023-08-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0006_propertyimages"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PropertyImages",
            new_name="PropertyImage",
        ),
        migrations.AddField(
            model_name="property",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="haji_salam.propertyimage",
            ),
        ),
    ]
