# Generated by Django 4.1.3 on 2023-08-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0007_rename_propertyimages_propertyimage_property_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="image",
        ),
        migrations.AddField(
            model_name="property",
            name="image",
            field=models.ManyToManyField(to="haji_salam.propertyimage"),
        ),
    ]
