# Generated by Django 4.1.3 on 2023-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0009_remove_property_image_propertyimage_property"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyimage",
            name="property",
        ),
        migrations.AddField(
            model_name="property",
            name="image",
            field=models.ManyToManyField(to="haji_salam.propertyimage"),
        ),
    ]
