# Generated by Django 4.1.3 on 2023-08-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0010_remove_propertyimage_property_property_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("image", models.FileField(blank=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.FileField(upload_to="images/")),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="haji_salam.post",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="property",
            name="city",
        ),
        migrations.RemoveField(
            model_name="property",
            name="image",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Property",
        ),
        migrations.DeleteModel(
            name="PropertyImage",
        ),
    ]
