# Generated by Django 4.1.3 on 2023-08-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0011_post_postimage_remove_property_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.IntegerField(null=True)),
                (
                    "Purpose",
                    models.CharField(
                        choices=[("Sale", "Sale"), ("Rent", "Rent")],
                        default="Sale",
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("House", "House"),
                            ("Villa", "Villa"),
                            ("Apartment", "Apartment"),
                            ("Office", "Office"),
                            ("Land", "Land"),
                            ("Shop", "Shop"),
                            ("Market", "Market"),
                            ("Building", "Building"),
                            ("Farm", "Farm"),
                        ],
                        default="House",
                        max_length=35,
                    ),
                ),
                ("area", models.IntegerField(null=True)),
                ("bedrooms", models.IntegerField(null=True)),
                ("reception_rooms", models.IntegerField(null=True)),
                ("bathrooms", models.IntegerField(null=True)),
                ("furnishing", models.BooleanField(default=False)),
                ("garden", models.BooleanField(default=False)),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="haji_salam.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="images")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="haji_salam.property",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="postimage",
            name="post",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="PostImage",
        ),
    ]
