# Generated by Django 4.1.3 on 2023-08-27 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "haji_salam",
            "0012_city_property_propertyimage_remove_postimage_post_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="haji_salam.city",
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="haji_salam.property",
            ),
        ),
    ]
