# Generated by Django 4.1.3 on 2023-08-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0013_property_date_alter_property_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="date",
            field=models.DateField(),
        ),
    ]
