# Generated by Django 4.1.3 on 2023-08-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0014_alter_property_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="neighborhood_or_project",
            field=models.CharField(max_length=35, null=True),
        ),
    ]
