# Generated by Django 4.1.3 on 2023-08-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0015_property_neighborhood_or_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="main_image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
