# Generated by Django 4.1.3 on 2023-08-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "haji_salam",
            "0017_alter_property_bathrooms_alter_property_bedrooms_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
