# Generated by Django 4.1.3 on 2023-08-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0018_alter_property_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
