# Generated by Django 4.1.3 on 2023-08-29 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0019_alter_property_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="property",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
