# Generated by Django 4.1.3 on 2023-08-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0020_property_featured_alter_property_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="Purpose",
            new_name="purpose",
        ),
    ]
