# Generated by Django 4.1.3 on 2023-08-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0021_rename_purpose_property_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
