# Generated by Django 4.1.3 on 2023-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0022_alter_property_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="prop_slug",
            field=models.SlugField(
                default=models.CharField(max_length=255), unique=True
            ),
        ),
    ]
