# Generated by Django 4.1.3 on 2023-08-31 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0025_alter_property_prop_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="prop_slug",
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
