# Generated by Django 4.1.3 on 2023-08-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0031_alter_property_prop_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="prop_slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
