# Generated by Django 4.1.3 on 2023-08-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0032_alter_property_prop_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
