# Generated by Django 4.1.3 on 2023-08-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0033_alter_property_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="type",
            field=models.CharField(
                choices=[
                    ("House", "House"),
                    ("Villa", "Villa"),
                    ("Apartment", "Apartment"),
                    ("Commercial Apartment", "Commercial Apartment"),
                    ("Office", "Office"),
                    ("Land", "Land"),
                    ("Shop", "Shop"),
                    ("Market", "Market"),
                    ("Building", "Building"),
                    ("Farm", "Farm"),
                ],
                default="House",
                max_length=35,
            ),
        ),
    ]
