# Generated by Django 4.2.3 on 2023-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0034_alter_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="balcony",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="garage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="kitchens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
