# Generated by Django 4.1.3 on 2023-09-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0035_property_balcony_property_garage_property_kitchens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(
                choices=[
                    ("erbil", "erbil"),
                    ("sulaymaniah", "sulaymaniah"),
                    ("duhok", "duhok"),
                ],
                default="erbil",
                max_length=35,
            ),
        ),
        migrations.DeleteModel(
            name="City",
        ),
    ]
