# Generated by Django 4.1.3 on 2023-09-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0040_property_projects"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="projects",
            new_name="project",
        ),
    ]
