# Generated by Django 4.1.3 on 2023-09-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0042_remove_property_neighborhood_or_project_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="neighborhood",
            new_name="region",
        ),
    ]
