# Generated by Django 4.1.3 on 2023-09-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haji_salam", "0044_alter_property_purpose_alter_property_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="type",
            field=models.CharField(
                choices=[
                    ("House", "House"),
                    ("Villa", "Villa"),
                    ("Apartment", "Apartment"),
                    ("Commercial Apartment", "Commercial Apartment"),
                    ("Office", "Office"),
                    ("Land", "Land"),
                    ("Residential Land", "Residential Land"),
                    ("Shop", "Shop"),
                    ("Market", "Market"),
                    ("Building", "Building"),
                    ("Farm", "Farm"),
                    ("Medical Center", "Medical Center"),
                    ("Restaurant", "Restaurant"),
                    ("Hotel", "Hotel"),
                ],
                default="House",
                max_length=35,
            ),
        ),
    ]
